spring:
  cloud:
    gateway:
      routes:
        - id: test_rout
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu
        - id: qq_rout
          uri: https://www.qq.com
          predicates:
            - Query=url,qq
        - id: product_rout
          uri: lb://mall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}